database:
    host: "localhost"
    database: "havania"
    username: "root"
    password: ""
server:
    id: 0
    type: "RUSH"
    bungee-name: "rush0"
    name: "Rush 4x1"
    size: 8
spawn:
    World: world
    X: 0
    Y: 100
    Z: 0
    Yaw: 0
    Pitch: 90
update-server-list: false